---
title: "eval-ubin-fscore"
author: "TB"
date: "3/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##load packages

```{r libraries}
library(data.table)
library(ggplot2)
library(tidyverse)
```

## Load data
```{r data, echo=FALSE}
setwd('/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/Evaluation_new_uBin/med_Compl/S1')
tb <-read.table('evaluation_overview_med_S1_das_Tool_uBin_new_evaluation.txt',sep='\t',header=F)[,c(13,14,15)]
colnames(tb) <- c("gold",'dastool','ubin')
```


## calc fscore
```{r fscorecalc}
dt <- data.table(tb)
#dt[,.(which.max(gold)),by=dastool]
dt[dastool=="medcomplmaxbin107.093.fasta_sub",names(which.max(table(gold)))]
dastool <- dt[,c(1,2)]
ubin <- dt[,c(1,3)]
binmatcherdastool <- dastool[,.('dastoolgoldstdname'=names(which.max(table(gold)))),by=dastool]
binmatcherubin <- ubin[,.('ubingoldstdname'=names(which.max(table(gold)))),by=ubin]
setkey(binmatcherdastool,"dastool")
setkey(binmatcherubin,"ubin")
setkey(dastool,"dastool")
setkey(ubin,'ubin')
dastoolwmatch <- data.table(merge(dastool,binmatcherdastool))
ubinwmatch <- merge(ubin,binmatcherubin)
```

```{r dastool}
dastoolwmatch <- data.table(merge(dastool,binmatcherdastool))
colnames(dastoolwmatch)
countsgoldstd <- table(dastoolwmatch[,gold])
goldstcounts <- data.table(cbind('gold' = names(countsgoldstd),'countgoldstd' = unlist(countsgoldstd)))
setkey(goldstcounts,"gold")
setkey(dastoolwmatch,"gold")
mergeddastool <- merge(dastoolwmatch,goldstcounts)
mergeddastool[,countgoldstd:=as.numeric(countgoldstd)]
#recalldastool
recalldastool <- mergeddastool[gold==dastoolgoldstdname,.('recall'=.N / max(countgoldstd)),by=dastool]
#precision das tool
mergeddastool[,'totaldastool':=.N,by=dastool]
precisiondastool <- mergeddastool[gold==dastoolgoldstdname,.('precision'=.N / max(totaldastool)),by=dastool]
setkey(recalldastool,'dastool')
setkey(precisiondastool,'dastool')
precrecall <- merge(recalldastool,precisiondastool)
precrecall[,'fscore':=(recall+precision)/2]
dastoolprecrecall <- precrecall
```

```{r ubin}
ubinwmatch <- merge(ubin,binmatcherubin)
colnames(ubinwmatch)[1] <- 'dastool'
dastoolwmatch <- ubinwmatch
colnames(dastoolwmatch)
countsgoldstd <- table(dastoolwmatch[,gold])
goldstcounts <- data.table(cbind('gold' = names(countsgoldstd),'countgoldstd' = unlist(countsgoldstd)))
setkey(goldstcounts,"gold")
setkey(dastoolwmatch,"gold")
mergeddastool <- merge(dastoolwmatch,goldstcounts)
mergeddastool[,countgoldstd:=as.numeric(countgoldstd)]
#recalldastool
recalldastool <- mergeddastool[gold==ubingoldstdname,.('recall'=.N / max(countgoldstd)),by=dastool]
#precision das tool
mergeddastool[,'totaldastool':=.N,by=dastool]
precisiondastool <- mergeddastool[gold==ubingoldstdname,.('precision'=.N / max(totaldastool)),by=dastool]
setkey(recalldastool,'dastool')
setkey(precisiondastool,'dastool')
precrecall <- merge(recalldastool,precisiondastool)
precrecall[,'fscore':=(recall+precision)/2]
ubinprecrecall <- precrecall
```

```{r plotting}
ubinprecrecall[,'toolname':='uBin']
dastoolprecrecall[,'toolname':='Das tool']
fusedtable <- rbind(ubinprecrecall,dastoolprecrecall)
ggplot(fusedtable,aes(x=toolname,y=fscore))+
  geom_violin(fill='burlywood2')+
  geom_point()+
  theme_bw()+
  theme(panel.grid=element_blank())
```

```{r PuttingItAllInAFunction}


## inputs pathtotable
parsingdastooluBintables <- function(pathtotable,datatype){
  
  #loading packs
library(data.table)
library(ggplot2)
library(tidyverse)
  ##readindata
tb <-read.table(pathtotable,sep='\t',header=F)[,c(13,14,15)]
head(tb)
colnames(tb) <- c("gold",'dastool','ubin')
dt <- data.table(tb)
print(dt)
## parse data
#dt[,.(which.max(gold)),by=dastool]
dt[dastool=="medcomplmaxbin107.093.fasta_sub",names(which.max(table(gold)))]
dastool <- dt[,c(1,2)]
ubin <- dt[,c(1,3)]
binmatcherdastool <- dastool[,.('dastoolgoldstdname'=names(which.max(table(gold)))),by=dastool]
binmatcherubin <- ubin[,.('ubingoldstdname'=names(which.max(table(gold)))),by=ubin]
setkey(binmatcherdastool,"dastool")
setkey(binmatcherubin,"ubin")
setkey(dastool,"dastool")
setkey(ubin,'ubin')
dastoolwmatch <- data.table(merge(dastool,binmatcherdastool))
ubinwmatch <- merge(ubin,binmatcherubin)

#parse dastool
dastoolwmatch <- data.table(merge(dastool,binmatcherdastool))
colnames(dastoolwmatch)
countsgoldstd <- table(dastoolwmatch[,gold])
goldstcounts <- data.table(cbind('gold' = names(countsgoldstd),'countgoldstd' = unlist(countsgoldstd)))
setkey(goldstcounts,"gold")
setkey(dastoolwmatch,"gold")
mergeddastool <- merge(dastoolwmatch,goldstcounts)
mergeddastool[,countgoldstd:=as.numeric(countgoldstd)]
#recalldastool
recalldastool <- mergeddastool[gold==dastoolgoldstdname,.('recall'=.N / max(countgoldstd)),by=dastool]
#precision das tool
mergeddastool[,'totaldastool':=.N,by=dastool]
precisiondastool <- mergeddastool[gold==dastoolgoldstdname,.('precision'=.N / max(totaldastool)),by=dastool]
setkey(recalldastool,'dastool')
setkey(precisiondastool,'dastool')
precrecall <- merge(recalldastool,precisiondastool)
precrecall[,'fscore':=(recall+precision)/2]
dastoolprecrecall <- precrecall
# parse ubin
ubinwmatch <- merge(ubin,binmatcherubin)
colnames(ubinwmatch)[1] <- 'dastool'
dastoolwmatch <- ubinwmatch
colnames(dastoolwmatch)
countsgoldstd <- table(dastoolwmatch[,gold])
goldstcounts <- data.table(cbind('gold' = names(countsgoldstd),'countgoldstd' = unlist(countsgoldstd)))
setkey(goldstcounts,"gold")
setkey(dastoolwmatch,"gold")
mergeddastool <- merge(dastoolwmatch,goldstcounts)
mergeddastool[,countgoldstd:=as.numeric(countgoldstd)]
#recalldastool
recalldastool <- mergeddastool[gold==ubingoldstdname,.('recall'=.N / max(countgoldstd)),by=dastool]
#precision das tool
mergeddastool[,'totaldastool':=.N,by=dastool]
precisiondastool <- mergeddastool[gold==ubingoldstdname,.('precision'=.N / max(totaldastool)),by=dastool]
setkey(recalldastool,'dastool')
setkey(precisiondastool,'dastool')
precrecall <- merge(recalldastool,precisiondastool)
precrecall[,'fscore':=(recall+precision)/2]
ubinprecrecall <- precrecall
# fuse table
ubinprecrecall[,'toolname':='uBin']
dastoolprecrecall[,'toolname':='Das tool']
fusedtable <- rbind(ubinprecrecall,dastoolprecrecall)
fusedtable[,'datatype':=datatype]
return(fusedtable)
}
```

```{r executionfunction, message=TRUE, warning=TRUE}
pathstotables <- c(
                   "/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/Evaluation_new_uBin/tables_complexity_gathered/mediumS1_complexity_dastool_uBin.tsv",
                   "/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/Evaluation_new_uBin/tables_complexity_gathered/highcomplexity_dastool_ubin.tsv","/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/Evaluation_new_uBin/tables_complexity_gathered/low_complexity_dastool_uBin_modtobe15collong.tsv" )

datatypes <- c("medium","high","low")
dfwithall <- data.frame()
for(i in 1:3){
  print(i)
  print(pathstotables[i])
  results <- parsingdastooluBintables(pathtotable=pathstotables[i],datatype=datatypes[i])
  dfwithall <- rbind(dfwithall,results)
}
```
```{r plottingentireCAMI}
dfwithall
dfwithall[,datatype:=factor(datatype,levels=c('low','medium','high'))]
ggplot(data=dfwithall,aes(x=toolname,y=fscore))+
  geom_violin(fill="burlywood2")+
  geom_point()+
  facet_wrap(datatype~.)+
  theme_bw()+
  theme(panel.grid=element_blank(),strip.background = element_rect(
     color="black", fill="white", size=0, linetype="solid"
     ))

ggsave("/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/Evaluation_new_uBin/tables_complexity_gathered/violinplot_fscore_all_complexities.pdf",device='pdf')

```
```{r basicstats_unpaired}
for(i in unique(dfwithall$datatype)){
  print(i)
  print('ttest')
  print(t.test(dfwithall[datatype==i,][toolname=="Das tool",fscore],dfwithall[datatype==i,][toolname=="uBin",fscore]))
  print("kruskal")
  print(kruskal.test(,x=dfwithall[datatype==i,fscore],g=dfwithall[datatype==i,toolname]))

print('aov')
print(summary(aov(data=dfwithall[datatype==i,],fscore~toolname)))
print('tukey')
print(TukeyHSD(aov(data=dfwithall[datatype==i,],fscore~toolname)))
}
```
```{r matchingubintodastoolbins}
  #loading packs
extractmatchesofdastooltoubin <- function(pathtotable,datatype){
library(data.table)
library(ggplot2)
library(tidyverse)
  ##readindata
tb <-read.table(pathtotable,sep='\t',header=F)[,c(13,14,15)]
#head(tb)
colnames(tb) <- c("gold",'dastool','ubin')
dt <- data.table(tb)
#print(dt)
## parse data
#dt[,.(which.max(gold)),by=dastool]
#dt[dastool=="medcomplmaxbin107.093.fasta_sub",names(which.max(table(gold)))]

#dt[dastool=="medcomplmaxbin107.093.fasta_sub",names(which.max(table(gold)))]
dastooltoubin <- dt[,c(2,3)]
binmatcherdastool <- dastooltoubin[,.('ubindastoolbinname'=names(which.max(table(dastool)))),by=ubin]
binmatcherdastool[,'datatype':=datatype]
return(binmatcherdastool)
}
dataframeofmatches <- data.frame()
for(i in 1:length(pathstotables)){
match <- extractmatchesofdastooltoubin(pathstotables[i],datatypes[i])
dataframeofmatches <- rbind(dataframeofmatches,match)
}

subset <- dfwithall[,.(dastool,fscore)]
colnames(subset)[1] <- "ubindastoolbinname"

### check gt symbol p value -done
#check if blanks around >< -done
## fscore write the same -done
## add defintion of rps3 high/med compl. datasets
## this is an estimate of cpmpl. based on diversity but can also stem from other factors including varying coverage annd similar kmer freq distributions
#add tests species difference
## do equivalence tests PMA


setkey(subset,'ubindastoolbinname')
setkey(dataframeofmatches,'ubindastoolbinname')
dataframeofmatches <- dataframeofmatches[!(ubindastoolbinname=="" | ubin==""),]

dastoolfscoreadded <- merge(x=dataframeofmatches,y=subset,all.x=T)
colnames(dastoolfscoreadded)[4] <- "dastoolfscore"
setkey(dastoolfscoreadded,'ubin')
subset <- dfwithall[,.(dastool,fscore,datatype)]
colnames(subset)[1] <- "ubin"
setkey(subset,'ubin')
fscoresofbothadded <- merge(x=dastoolfscoreadded,y=subset,all.x=T)
colnames(fscoresofbothadded)[5] <- "fscoreubin"
fscoresofbothadded <-unique(fscoresofbothadded)
fscoresofbothadded[,datatype.x:=factor(datatype.x,levels=c('low','medium','high'))]


## percent of bins with higher fscore in ubin than dastool -> 78.9%
sum(fscoresofbothadded$fscoreubin-fscoresofbothadded$dastoolfscore >0) / 161

```







```{r pairedtests}
head(fscoresofbothadded)

for(i in unique(fscoresofbothadded$datatype.x)){
  sub <- fscoresofbothadded[datatype.x==i,]
  print(i)
  print(t.test(sub$dastoolfscore,sub$fscoreubin,paired=T)$p.value)

}
ggplot(data=fscoresofbothadded,aes(x=fscoreubin-dastoolfscore))+
    geom_histogram(fill="burlywood2")+
  geom_density(alpha=0.6,color='burlywood3')+
  facet_wrap(datatype.x~.)+
    theme_bw()+
    scale_y_continuous(limits = c(0,25))+
    theme(panel.grid=element_blank(),strip.background = element_rect(
     color="black", fill="white", size=0, linetype="solid"
     ))
    ggsave(device='pdf',"/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/Evaluation_new_uBin/tables_complexity_gathered/fscoredifference-pairedubindastoolhistogramplots.pdf")
```
```{r comparison_dastoolanduBinaccrossdatasetsseparately}
## dastool
subset <- dfwithall[toolname=='Das tool',]
summary(aov(data=subset,fscore~datatype)) ## p,10-5
TukeyHSD(aov(data=subset,fscore~datatype))

ggplot(data=subset,aes(x=datatype,y=fscore))+
  geom_violin(fill='burlywood2')+
  geom_point()+
  theme_bw()+
  theme(panel.grid=element_blank())
ggsave(device='pdf',"/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/Evaluation_new_uBin/tables_complexity_gathered/preuBin_CAMI_dataset_comparison.pdf")


subset[,.(mean(fscore),median(fscore)),by=datatype]
```
```{r compubinaccrossdatasets}
subset <- dfwithall[toolname=='uBin',]
summary(aov(data=subset,fscore~datatype)) ## p,10-5
TukeyHSD(aov(data=subset,fscore~datatype))
subset[,.(mean(fscore),median(fscore)),by=datatype]

ggplot(data=subset,aes(x=datatype,y=fscore))+
  geom_violin(fill='burlywood2')+
  geom_point()+
  theme_bw()+
  theme(panel.grid=element_blank())
ggsave(device='pdf',"/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/Evaluation_new_uBin/tables_complexity_gathered/postuBin_CAMI_dataset_comparison.pdf")


```


```{r tomskandsulcav}
setwd("/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables")
dir()

files <- c("tablecompleteness_tomskprecuration.tsv","tablecompleteness_tomsk_curated.tsv","tablecompleteness_sulcavas07_curated.tsv","tablecompleteness_sulcavas07_precuration.tsv")
naming <- c("tomsk_pre","tomsk_post","sulcav_post","sulcav_pre")
parsingtables <- function(file){
table <- read.table(file,sep='\t',header=T)
transformdecimals <- function(string,symbolseparator='/'){
  value <- as.numeric(unlist(strsplit(as.character(string),split='/'))[1]) / as.numeric(unlist(strsplit(as.character(string),split='/'))[2])
  return(value)
}
list2 <- ''
list3 <- ''
list5 <- ''
list6 <- ''

for(i in 1:length(table[,2])){
 list2 <- c(list2,transformdecimals(string=table[i,2],symbolseparator = '/') )
 list3 <- c(list3,transformdecimals(string=table[i,3],symbolseparator = '/') )
 list5 <- c(list5,transformdecimals(string=table[i,5],symbolseparator = '/') )
 list6 <- c(list6,transformdecimals(string=table[i,6],symbolseparator = '/') )
}
list2 <- as.numeric(list2[-1])
list3 <- as.numeric(list3[-1])
list5 <- as.numeric(list5[-1])
list6 <- as.numeric(list6[-1])

table[,2] <- list2
table[,3] <- list3
table[,5] <- list5
table[,6] <- list6
ubin <- data.table(table)
ubin
ubin[,'selectscgset':=ifelse(ArchSCG > BacSCG,'Archs','Bacs')]
ubin[,'SCGcor':=ifelse(selectscgset=='Bacs',BacSCG,ArchSCG)]
ubin[,'MSCGcor':=ifelse(selectscgset=='Bacs',BacMSCG,ArchMSCG)]
ubin[,'pseudofscore':=(SCGcor+SCGcor/(SCGcor+MSCGcor))/2]

ubin[,'pseudofscore2':=(SCGcor/(MSCGcor+SCGcor)+(SCGcor/(SCGcor+1-SCGcor)))/2]
return(ubin)
}

setwd("/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables")
results <- data.frame()
for(i in 1:length(files)){
  dftmp <- data.table(parsingtables(files[i]))
  dftmp[,'filename':=naming[i]]
  results <- rbind(results,dftmp)
}

results[,'tomskorsulcav':=ifelse(filename%in%c("sulcav_pre","sulcav_post"),'SulCav','Tomsk')]
ggplot(data=results,aes(x=filename,y=pseudofscore))+
  geom_violin(fill='burlywood2')+
  geom_point()
```
```{r Sulcavtomskchdb}
sulcur <- data.table(read.csv('/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables/Chdb_SulCav_curated.csv',sep=',',header=T))
sulpre <- data.table(read.csv('/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables/Chdb_SulCav_precuration.csv',sep=',',header=T))
tomcur <- data.table(read.csv('/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables/Chdb_Tomsk_curated.csv',sep=',',header=T))
tompre <- data.table(read.csv('/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables/Chdb_Tomsk_precuration.csv',sep=',',header=T))




sulcur<- sulcur[,c(1,6:8)]
sulpre <- sulpre[,c(1,6:8)]
tomcur<- tomcur[,c(1,6:8)]
tompre<- tompre[,c(1,6:8)]


sulcur[,'fscore':=((Completeness/100)+((Completeness/100)/((Completeness/100)+(Contamination/100))))/2]
sulcur[,Bin.Id:=gsub(Bin.Id,pattern=".fasta$",repl="")]
sulcur <- data.table(sulcur[,c(1,4,5)])

sulpre[,'fscore':=((Completeness/100)+((Completeness/100)/((Completeness/100)+(Contamination/100))))/2]
sulpre[,Bin.Id:=gsub(Bin.Id,pattern=".fasta$",repl="")]
sulpre <- data.table(sulpre[,c(1,4,5)])

tomcur[,'fscore':=((Completeness/100)+((Completeness/100)/((Completeness/100)+(Contamination/100))))/2]
tomcur[,Bin.Id:=gsub(Bin.Id,pattern=".fasta$",repl="")]
tomcur <- data.table(tomcur[,c(1,4,5)])

tompre[,'fscore':=((Completeness/100)+((Completeness/100)/((Completeness/100)+(Contamination/100))))/2]
tompre[,Bin.Id:=gsub(Bin.Id,pattern=".fasta$",repl="")]
tompre <- data.table(tompre[,c(1,4,5)])


#setkey(ubinstandalone,"Bin")
#setkey(dastool,'Bin')
#setkey(ubin,'Bin')

colnames(sulcur)[1] <- "Bin"
colnames(sulpre)[1] <- "Bin"
colnames(tomcur)[1] <- "Bin"
colnames(tompre)[1] <- "Bin"

togeterhcheckm<- rbind(sulcur,sulpre,tomcur,tompre)
setkey(togeterhcheckm,"Bin")
setkey(results,"Bin")
## 2 rows less in the dastool compl vals than in the checkm
colnames(results)[13] <- 'datatype'
colnames(results)[12] <- "toolname"
results$toolname[grep(results$toolname,pattern="_pre")] <- "Das tool"
results$toolname[grep(results$toolname,pattern="_post")] <- "uBin"




mergedonlnewvals <- merge(results,togeterhcheckm)

mergedonlnewvals
#dim(results)
#dim(togeterhcheckm)
results[,1]
```


```{r plotallunpaired}
dfwithall[,datatype:=factor(datatype,levels=c('low','medium','high'))]


colnames(results)[13] <- 'datatype'
colnames(results)[12] <- "toolname"
results$toolname[grep(results$toolname,pattern="_pre")] <- "Das tool"
results$toolname[grep(results$toolname,pattern="_post")] <- "uBin"


newcopy <- dfwithall
newcopy
#mergedSulCavtomskcami <- rbind(dfwithall,results)
subset <- results[,c(1,11:13)]
subset2 <- dfwithall[,c(1,4:6)]
colnames(subset) <- c("dastool","fscore" ,"toolname","datatype")
colnames(subset2)

fusedcamisulcavtomsk <- rbind(subset,subset2)

fusedcamisulcavtomsk[,datatype:=factor(datatype,levels=c('low','medium','high','Tomsk','SulCav'))]
ggplot(data=fusedcamisulcavtomsk,aes(x=toolname,y=fscore))+
  geom_violin(fill="burlywood2")+
  geom_point()+
  facet_wrap(datatype~.,nrow=1)+
  theme_bw()+
  theme(panel.grid=element_blank(),strip.background = element_rect(
     color="black", fill="white", size=0, linetype="solid"
     ))

for(i in unique(fusedcamisulcavtomsk$datatype)){
  print(i)
  print('ttest')
  print(t.test(fusedcamisulcavtomsk[datatype==i,][toolname=="Das tool",fscore],fusedcamisulcavtomsk[datatype==i,][toolname=="uBin",fscore]))

print('aov')
print(summary(aov(data=fusedcamisulcavtomsk[datatype==i,],fscore~toolname)))
print('tukey')
print(TukeyHSD(aov(data=fusedcamisulcavtomsk[datatype==i,],fscore~toolname)))
}

```
```{r plotallunpaired_withcheckmvals}
dfwithall[,datatype:=factor(datatype,levels=c('low','medium','high'))]
mergedonlnewvals


#colnames(results)[13] <- 'datatype'
#colnames(results)[12] <- "toolname"
results$toolname[grep(results$toolname,pattern="_pre")] <- "Das tool"
results$toolname[grep(results$toolname,pattern="_post")] <- "uBin"


#newcopy <- dfwithall
#newcopy
#mergedSulCavtomskcami <- rbind(dfwithall,results)
subset <- mergedonlnewvals[,.(Bin,fscore,toolname,datatype)]
subset <- subset[,.(Bin,fscore,toolname,datatype)]
subset2 <- dfwithall[,c(1,4:6)]
colnames(subset) <- c("dastool","fscore" ,"toolname","datatype")
colnames(subset2)

fusedcamisulcavtomsk <- rbind(subset,subset2)

fusedcamisulcavtomsk[,datatype:=factor(datatype,levels=c('low','medium','high','Tomsk','SulCav'))]
ggplot(data=fusedcamisulcavtomsk,aes(x=toolname,y=fscore))+
  geom_violin(fill="burlywood2")+
  geom_point()+
  facet_wrap(datatype~.,nrow=1)+
  theme_bw()+
  theme(panel.grid=element_blank(),strip.background = element_rect(
     color="black", fill="white", size=0, linetype="solid"
     ))
ggsave("/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables/plotviolin_all_unpairedchdb.pdf",device='pdf')


for(i in unique(fusedcamisulcavtomsk$datatype)){
  print(i)
  print('ttest')
  print(t.test(fusedcamisulcavtomsk[datatype==i,][toolname=="Das tool",fscore],fusedcamisulcavtomsk[datatype==i,][toolname=="uBin",fscore]))
  print('kruskal')
print(kruskal.test(x=fusedcamisulcavtomsk[datatype==i,fscore],g=fusedcamisulcavtomsk[datatype==i,toolname]))
print('aov')
print(summary(aov(data=fusedcamisulcavtomsk[datatype==i,],fscore~toolname)))
print('tukey')
print(TukeyHSD(aov(data=fusedcamisulcavtomsk[datatype==i,],fscore~toolname)))
}





```

```{r mmatchingbinssulcavtomsk}
#tomsk
setwd("/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables")
bubin <- data.table(read.table("DAS_tool_DASTool_scaffolds2bin_tomsk_precuration.txt",header=F,sep='\t'))
colnames(bubin) <- c('scaffold','bubin')
aubin <- data.table(read.table("scaf2bin_tomsk_curated.tsv",sep='\t',header=F))
colnames(aubin)<- c('scaffold','aubin')



merged2 <- merge(bubin,aubin,all=T)

colnames(merged2)

datatablebubinaubin <- data.frame()
for(i in unique(merged2[,bubin])){
  value <- merged2[bubin==i,names(which.max(table(aubin)))]
  values <- cbind('bubin'=i,'aubin'=value)
  datatablebubinaubin <- rbind(datatablebubinaubin,values)
}

tomskbinmatch <- data.table(datatablebubinaubin)
tomskbinmatch[,'dastoolfscore':=NA]
tomskbinmatch[,'ubinfscore':=NA]
## SulCav
setwd("/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables")
bubin <- data.table(read.table("das_tool_DASTool_scaffolds2bin_sulcavas07_precuration.txt",header=F,sep='\t'))
colnames(bubin) <- c('scaffold','bubin')
aubin <- data.table(read.table("scaf2bin_sulcavas07_curated.tsv",sep='\t',header=F))
colnames(aubin)<- c('scaffold','aubin')



merged2 <- merge(bubin,aubin,all=T)
#merged2 <- merged2[,c(1,6,11,16)]
colnames(merged2)

datatablebubinaubin <- data.frame()
for(i in unique(merged2[,bubin])){
  value <- merged2[bubin==i,names(which.max(table(aubin)))]
  values <- cbind('bubin'=i,'aubin'=value)
  datatablebubinaubin <- rbind(datatablebubinaubin,values)
}

sulcavbinmatch <- data.table(datatablebubinaubin)
sulcavbinmatch[,'dastoolfscore':=NA]
sulcavbinmatch[,'ubinfscore':=NA]

## fscoreaddition
tomskbinmatch[,'datatype':='Tomsk']
sulcavbinmatch[,'datatype':='SulCav']
fusedlists <- data.table(rbind(tomskbinmatch,sulcavbinmatch))
fusedlists[,aubin:=gsub(aubin,pattern=".fasta$",repl="")]
fusedlists[,bubin:=gsub(bubin,pattern=".fasta_M.*$",repl="")]
fusedlists[,bubin:=gsub(bubin,pattern=".fasta_aba.*$",repl="aba")]
fusedlists[,bubin:=gsub(bubin,pattern=".fasta_AS07.*$",repl="aba")]

fusedlists[,bubin:=ifelse(!(bubin %in% fusedcamisulcavtomsk[,dastool]),gsub(bubin,pattern='aba',repl=''),bubin)]
fusedcamisulcavtomsk


fscoreaubin <- list()
namesaubin <- list()
datatypeaubin <- list()
fscorebubin <- list()
namesbubin <- list()
datatypebubin <- list()



for(i in 1:length(fusedlists[,aubin])){
  if(fusedlists[i,aubin]!=""){
    fscoreaubin <- c(fscoreaubin,fusedcamisulcavtomsk[fusedcamisulcavtomsk[,dastool]%in%fusedlists[i,aubin],fscore])
    namesaubin <- c(namesaubin,as.character(fusedlists[i,aubin]))
    datatypeaubin <- c(datatypeaubin,as.character(fusedlists[i,datatype]))
  }
  if(fusedlists[i,bubin]!=""){
    fscorebubin <- c(fscorebubin,fusedcamisulcavtomsk[fusedcamisulcavtomsk[,dastool] %in% fusedlists[i,bubin],fscore])
    namesbubin <- c(namesbubin,as.character(fusedlists[i,bubin]))
    datatypebubin <- c(datatypeaubin,as.character(fusedlists[i,datatype]))
  }
}


####### I dont get why there is one sulcav entry too mmuch in datatypebubin and nnot in the others
# is provisorically fixed in concat table below but the reason remains unclear #WeirdStuff


fuseddftomsksulcavfscores <- data.table(data.frame(
                       'dastool_name'=unlist(namesbubin),
                       'ubin_name' = unlist(namesaubin),
                       'fscore_dastool' = unlist(fscorebubin),
                       'fscore_ubin' =  unlist(fscoreaubin),
                       'datatype_dastool' = unlist(datatypebubin[-length(datatypebubin)]),
                       'datatype_ubin' = unlist(datatypeaubin) 
))
          
sub1 <- fuseddftomsksulcavfscores[,c(1,2,3,4,5)]     
sub2 <- fscoresofbothadded[,c(2,1,4,5,6)]
colnames(sub1) <- c("dsatoolbin","ubinbin","dastoolscore","ubinscore","datatype")
colnames(sub2) <- c("dsatoolbin","ubinbin","dastoolscore","ubinscore","datatype")
fusedtableall <- data.table(rbind(sub1,sub2))
```

```{r pairedtests_sulctomskadded}
head(fscoresofbothadded)

for(i in unique(fusedtableall$datatype)){
  sub <- fusedtableall[datatype==i,]
  print(i)
  print(t.test(sub$dastoolscore,sub$ubinscore,paired=T)$p.value)
}

fusedtableall[,datatype:=factor(datatype,levels=c('low',"medium","high","Tomsk","SulCav"))]

ggplot(data=fusedtableall,aes(x=ubinscore-dastoolscore))+
    geom_histogram(fill="burlywood2")+
  geom_density(alpha=0.6,color='burlywood3')+
  facet_wrap(datatype~.,nrow=1)+
    theme_bw()+
    scale_y_continuous(limits = c(0,25))+
    theme(panel.grid=element_blank(),strip.background = element_rect(
     color="black", fill="white", size=0, linetype="solid"
     ))

ggsave("/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables/plotviolin_all_paired.pdf",device='pdf')

```
```{r aadditiontounpairedplot}
colnames(dfwithall)
colnames(results)
sub1 <- dfwithall[,c(1,4,5,6)]
sub2 <- results[,c(1,10,12,13)]

colnames(sub2) <- c( "dastool","fscore","toolname","datatype")
fuseddtwithnopairing <- data.table(rbind(sub1,sub2))

fuseddtwithnopairing[,datatype:=factor(datatype,levels=c('low','medium','high','Tomsk',"SulCav"))]
ggplot(data=fuseddtwithnopairing,aes(x=toolname,y=fscore))+
  geom_violin(fill="burlywood2")+
  geom_point()+
  facet_wrap(datatype~.,nrow=1)+
  theme_bw()+
  theme(panel.grid=element_blank(),strip.background = element_rect(
     color="black", fill="white", size=0, linetype="solid"
     ))
ggsave("/Users/tillbornemann/Documents/Students_theses/Lennard_Stach/SulCav_Tomskcompletiontables/plotviolin_all_unpaired.pdf",device='pdf')






```
